"""add_license_management

Revision ID: 167d9228199c
Revises: d31cb7dbef98
Create Date: 2026-02-11 17:42:49.306857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167d9228199c'
down_revision = 'd31cb7dbef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_license_key', sa.Text(), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('purchase_order', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('support_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('vendor_contact', sa.String(length=255), nullable=True),
    sa.Column('support_plan', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('encryption_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_name'), ['name'], unique=False)

    op.create_table('license_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('unassigned_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('machine_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('license_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_assignments_license_id'), ['license_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_license_assignments_license_id'))

    op.drop_table('license_assignments')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_name'))
        batch_op.drop_index(batch_op.f('ix_licenses_expiration_date'))

    op.drop_table('licenses')
    # ### end Alembic commands ###
