"""add_application_inventory

Revision ID: 19aaaec39038
Revises: fc29dac6cf77
Create Date: 2026-02-12 23:04:23.351607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19aaaec39038'
down_revision = 'fc29dac6cf77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('database_type', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('deployment_type', sa.String(length=50), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=True),
    sa.Column('sla_level', sa.String(length=20), nullable=True),
    sa.Column('criticality', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_server_name'), ['server_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_server_name'))
        batch_op.drop_index(batch_op.f('ix_applications_name'))

    op.drop_table('applications')
    # ### end Alembic commands ###
