"""license_assignment_freetext

Revision ID: fc29dac6cf77
Revises: 167d9228199c
Create Date: 2026-02-11 17:51:46.145378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc29dac6cf77'
down_revision = '167d9228199c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_license_assignments_user_id'))
        batch_op.drop_constraint(batch_op.f('FK__license_a__user___5441852A'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__license_a__user___5441852A'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_license_assignments_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
